@extends('studio.layout', ['active' => 'homepage'])
@section('title','Homepage')
@section('content')
@php($home=$data['homepage'])
<h1>Homepage content</h1><p class="lede">Manage the words, calls to action, and featured content. The preloader animation stays in code.</p>
<form method="post" action="{{ route('studio.homepage.save') }}">@csrf
<h2>Hero</h2><div class="form-grid">
<label class="full">Headline<input name="hero_headline" value="{{ old('hero_headline',$home['hero']['headline'] ?? '') }}"></label><label class="full">Supporting text<textarea name="hero_supporting">{{ old('hero_supporting',$home['hero']['supporting'] ?? '') }}</textarea></label>
<label>Primary CTA<input name="hero_cta_label" value="{{ old('hero_cta_label',$home['hero']['cta_label'] ?? '') }}"></label><label>Primary URL<input name="hero_cta_url" value="{{ old('hero_cta_url',$home['hero']['cta_url'] ?? '') }}"></label>
<label>Secondary CTA<input name="hero_secondary_cta_label" value="{{ old('hero_secondary_cta_label',$home['hero']['secondary_cta_label'] ?? '') }}"></label><label>Secondary URL<input name="hero_secondary_cta_url" value="{{ old('hero_secondary_cta_url',$home['hero']['secondary_cta_url'] ?? '') }}"></label></div>
<h2>Services intro</h2><div class="form-grid"><label>Title<input name="svc_title" value="{{ old('svc_title',$home['services_intro']['title'] ?? '') }}"></label><label>Statement<input name="svc_statement" value="{{ old('svc_statement',$home['services_intro']['statement'] ?? '') }}"></label><label class="full">Supporting<textarea name="svc_supporting">{{ old('svc_supporting',$home['services_intro']['supporting'] ?? '') }}</textarea></label></div>
<h2>About</h2><div class="form-grid"><label>Title<input name="about_title" value="{{ old('about_title',$home['about']['title'] ?? '') }}"></label><label>Main statement<input name="about_main" value="{{ old('about_main',$home['about']['main_statement'] ?? '') }}"></label><label class="full">Description<textarea name="about_description">{{ old('about_description',$home['about']['description'] ?? '') }}</textarea></label><label class="full">Mission<textarea name="about_mission">{{ old('about_mission',$home['about']['mission'] ?? '') }}</textarea></label><label class="full">Vision<textarea name="about_vision">{{ old('about_vision',$home['about']['vision'] ?? '') }}</textarea></label><label class="full">How we work<textarea name="about_how">{{ old('about_how',$home['about']['how_we_work'] ?? '') }}</textarea></label></div>
<h2>Call to action</h2><div class="form-grid"><label>Headline<input name="cta_headline" value="{{ old('cta_headline',$home['cta']['headline'] ?? '') }}"></label><label>Button<input name="cta_label" value="{{ old('cta_label',$home['cta']['cta_label'] ?? '') }}"></label><label class="full">Supporting<input name="cta_supporting" value="{{ old('cta_supporting',$home['cta']['supporting'] ?? '') }}"></label><label>Destination<input name="cta_url" value="{{ old('cta_url',$home['cta']['cta_url'] ?? '') }}"></label></div>
@foreach([['Featured projects','featured_project_slugs',$data['projects'] ?? [],'title'],['Featured case studies','featured_case_study_slugs',$data['case_studies'] ?? [],'title'],['Clients on homepage','featured_client_slugs',$data['clients'] ?? [],'name']] as [$heading,$field,$items,$label])
<h2>{{ $heading }}</h2><div class="checks">@forelse($items as $item)<label><input type="checkbox" name="{{ $field }}[]" value="{{ $item['slug'] }}" @checked(in_array($item['slug'],old($field,$home[$field] ?? [])))> {{ $item[$label] }} @if(isset($item['status']))({{ $item['status'] }})@endif</label>@empty<p class="note">None yet.</p>@endforelse</div>@endforeach
<button class="btn" style="margin-top:24px" type="submit">Save homepage</button></form>@endsection
